logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

downstream:
  baseurl: http://localhost:8081

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  cloud:
    gateway:
      routes:
        - id: user_route
          uri: ${downstream.baseurl:http://localhost:8081}
          predicates:
            - Path=/user-service/**
          filters:
            - RewritePath=/user-service/(?<subUrl>.*),/api/${subUrl}
            - RemoveResponseHeader=X-Powered-By
            - name: CircuitBreaker
              args:
                name: appCircuitBreaker
                fallbackUri: forward:/demo-app/fallback
        - id: protected-user-route
          uri: ${downstream.baseurl:http://localhost:8081}
          predicates:
            - Path=/special-user-service/users
          filters:
            - name: UserAuthentication
              args:
                headerName: Authorization
            - name: RateLimiter
              args:
                statusCode: TOO_MANY_REQUESTS
            - RewritePath=/special-user-service/users,/api/special-users

resilience4j:
  circuitbreaker:
    instances:
      appCircuitBreaker:
        slidingWindowSize: 100
        failureRateThreshold: 50
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10s
  timelimiter:
    instances:
      appCircuitBreaker:
        timeoutDuration: 5s


